SELECT SALES_DATE,PRODUCT_ID,USER_ID,(SALES_AMOUNT+SALES_AMOUNT) FROM ONLINE_SALE 
RIGHT JOIN OFFLINE_SALE ON ONLINE_SALE.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID

GROUP BY SALES_DATE


SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE , PRODUCT_ID, USER_ID,  SALES_AMOUNT 
FROM ONLINE_SALE
WHERE ONLINE_SALE.SALES_DATE LIKE '%2022-03%'
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d')  AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
 FROM OFFLINE_SALE
 WHERE OFFLINE_SALE.SALES_DATE LIKE '%2022-03%'




ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC



