SELECT 상품명, 가격 FROM PRODUCT

SELECT * FROM product ORDER BY 가격 


SELECT * FROM product ORDER BY 가격 ASC 카테고리 ASC

SELECT * FROM 직원테이블 ORDER BY 근무기간 ASC 이름 ASC


SELECT * FROM 테이블 WHERE 재고 <=20 ORDER BY 상품명 ASC

SELECT * FROM 테이블 WHERE 가격 <3000 OR 가격>6000

SELECT * FROM 테이블 WHERE NOT 카테고리='옷' AND 가격=5000

SELECT * FROM 테이블 WHERE  NOT 상품명 IN(셔츠,반팔티,운동화)

SELECT * FROM 테이블 WHERE 상품명 LIKE 'Green%chair'

SELECT * FROM 테이블 WHERE 상품명 LIKE '%소파%' OR 상품명 LIKE '%chair%'

SELECT * FROM 테이블 WHERE  상품명  LIKE '%소파%' AND NOT LIKE '%나무%'

SELECT AVG(사용금액) FROM 테이블 WHERE 고객등급='vip'

SELECT MAX(결제횟수),MIN(결제횟수) FROM 테이블

SELECT COUNT(연체횟수) FROM 테이블 WHERE '연체횟수'<2



SELECT FLAVOR FROM FIRST_HALF  ORDER BY TOTAL_ORDER DESC , SHIPMENT_ID ASC

SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID  ASC

SELECT MEMBER_ID,MEMBER_NAME,GENDER, DATE_FORMAT(DATE_OF_BIRTH ,'%Y-%m-%d') FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND DATE_OF_BIRTH LIKE '%-03-%'AND TLNO NOT LIKE 'NULL' ORDER BY MEMBER_ID ASC
 
 SELECT FLAVOR FROM FIRST_HAF WHERE TOTAL_ORDER>3000 ORDER BY TOTAL_ORDER ASC


SELECT SUBSTR(번호,10,4) FROM TABLE


SELECT COUNT(고객등급) FROM 테이블  WHERE 연체횟수 > (SELECT AVG(연체횟수) FROM 테이블 WHERE 고객등급 ='패밀리') 

 SELECT AVG(사용금액) FROM 테이블 


SELECT TOTAL_ORDER FROM FIRST_HALF WHERE >3000

SELECT FLAVOR FROM FIRST_HALF WHERE (SELECT TOTAL_ORDER FROM ICECREAM_INFO) 


SELECT FLAVOR FROM ICECREAM_INFO,FIRST_HALF WHERE INGREDIENT_TYPE ='fruit_based' AND (SELECT FLAVOR FROM FIRST_HALF WHERE TOTAL_ORDER >3000)

SELECT PT_NAME,PT_NO,GEND_CD,AGE,IFNULL(TLNO,'NONE')     FROM PATIENT WHERE AGE <=12 AND GEND_CD ='W' ORDER BY AGE DESC , PT_NAME ASC

SELECT  FORMAT() FROM DOCTOR WHERE MCDP_CD IN('GS','CS')  ORDER BY HIRE_YMD DESC, DR_NAME ASC